import { requireCap } from "@/lib/auth";
import { sql } from "@/lib/db";
import { money } from "@/lib/format";
import { createFinanceInvoice, recordFinancePayment, setFinanceInvoiceStatus } from "@/lib/actions/finance";
import { ActionForm, Dialog, Select, SubmitBtn } from "@/components/form";
import { Badge, Card, Empty, Field, PageHeader, Row, Table, Td } from "@/components/ui";

export const metadata={title:"Invoices"};
export default async function InvoicesPage(){const me=await requireCap("invoice.manage"); const [invoices,companies]=await Promise.all([sql<{id:number;ref:string;company:string|null;issue_date:string;due_date:string|null;currency:string;total:string;amount_paid:string;status:string}>`select i.*,c.name as company from crm_finance_invoices i left join crm_companies c on c.id=i.company_id order by i.created_at desc`,sql<{id:number;name:string}>`select id,name from crm_companies order by name`]); return <><PageHeader title="Invoices" subtitle="Client billing belongs to CRM."><Dialog label="New invoice" title="Create invoice"><ActionForm action={createFinanceInvoice} className="space-y-3"><Field label="Client"><Select name="company_id" className="field"><option value="">No linked client</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></Field><Field label="Description"><input name="description" required className="field"/></Field><Row><Field label="Quantity"><input name="quantity" type="number" min="0.01" step="0.01" defaultValue="1" className="field"/></Field><Field label="Unit price"><input name="unit_price" type="number" min="0" step="0.01" required className="field"/></Field></Row><Row><Field label="VAT %"><input name="tax_rate" type="number" min="0" step="0.01" defaultValue="7.5" className="field"/></Field><Field label="Due date"><input name="due_date" type="date" className="field"/></Field></Row><Field label="Notes"><textarea name="notes" className="field"/></Field><SubmitBtn className="w-full">Create draft</SubmitBtn></ActionForm></Dialog></PageHeader>{invoices.length===0?<Card><Empty title="No invoices yet"/></Card>:<Table head={["Reference","Client","Total","Paid","Status","Action"]}>{invoices.map(i=><tr key={i.id}><Td className="font-bold">{i.ref}</Td><Td>{i.company||"—"}</Td><Td>{money(Number(i.total),i.currency)}</Td><Td>{money(Number(i.amount_paid),i.currency)}</Td><Td><Badge value={i.status}/></Td><Td><div className="flex gap-2">{i.status==="draft"&&<ActionForm action={setFinanceInvoiceStatus}><input type="hidden" name="id" value={i.id}/><input type="hidden" name="status" value="sent"/><SubmitBtn variant="ghost">Send</SubmitBtn></ActionForm>}{["sent","part_paid"].includes(i.status)&&<Dialog label="Record payment" title={i.ref}><ActionForm action={recordFinancePayment} className="space-y-3"><input type="hidden" name="invoice_id" value={i.id}/><Field label="Amount"><input name="amount" type="number" min="0.01" step="0.01" className="field"/></Field><Field label="Reference"><input name="reference" className="field"/></Field><SubmitBtn className="w-full">Record payment</SubmitBtn></ActionForm></Dialog>}</div></Td></tr>)}</Table>}</>}
